// Types barrel for /design-sync — lets the converter enumerate the design
// system's public component surface (this repo ships no built dist/.d.ts).
// Mirrors ds-entry.tsx. Re-exports resolve to the real component source.
export { DocumentTypeTag } from '../components/primitives/DocumentTypeTag'
export { EpisodeStatusBadge } from '../components/primitives/EpisodeStatusBadge'
export { TaskCategoryIcon } from '../components/primitives/TaskCategoryIcon'
export { TranslationStatusIndicator } from '../components/primitives/TranslationStatusIndicator'
export { DocumentCard } from '../components/composites/DocumentCard'
export { EpisodeStatusCard } from '../components/composites/EpisodeStatusCard'
export { PendingTaskRow } from '../components/composites/PendingTaskRow'
export { CoordinatorSidebarNav } from '../components/features/CoordinatorSidebarNav'
export { CreateEpisodeButton } from '../components/features/CreateEpisodeButton'
export { CreatePatientForm } from '../components/features/CreatePatientForm'
export { DocumentClassificationEditor } from '../components/features/DocumentClassificationEditor'
export { DocumentUploadZone } from '../components/features/DocumentUploadZone'
export { DocumentsSection } from '../components/features/DocumentsSection'
export { EpisodeSummaryPanel } from '../components/features/EpisodeSummaryPanel'
export { EpisodeTimeline } from '../components/features/EpisodeTimeline'
export { PatientInviteButton } from '../components/features/PatientInviteButton'
export { PatientSummaryPanel } from '../components/features/PatientSummaryPanel'
export { PatientTabNav } from '../components/features/PatientTabNav'
export { PatientViewTabNav } from '../components/features/PatientViewTabNav'
export { RevokeAccessButton } from '../components/features/RevokeAccessButton'
export { TasksClient } from '../components/features/TasksClient'
export { TranslationOutputPanel } from '../components/features/TranslationOutputPanel'
export { UserProfileMenu } from '../components/features/UserProfileMenu'
