// Single source of truth for all input validation (CLAUDE.md stop condition:
// no action or form ships without a schema here). Zod v4 API.

import * as z from 'zod'
import { DOC_TYPES, PROFILE_COLORS, SEXES } from '@/lib/types/domain'

// ── Capture (Phase 2) ────────────────────────────────────────────────────────
// Client-upload token flow (D-003): sign → direct PUT → createDocument.
// Bytes never transit our server; these schemas gate the two round-trips that
// do (the signed-URL request and the post-upload DB write).

export const UPLOAD_MIME_TYPES = ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'] as const
export type UploadMimeType = (typeof UPLOAD_MIME_TYPES)[number]
export const MAX_UPLOAD_BYTES = 20 * 1024 * 1024 // 20MB — re-encoded photos land well under this

export const RequestUploadSchema = z.object({
  profileId: z.uuid(),
  mimeType: z.enum(UPLOAD_MIME_TYPES),
})
export type RequestUploadInput = z.infer<typeof RequestUploadSchema>

export const CreateDocumentSchema = z.object({
  profileId: z.uuid(),
  blobKey: z.string().min(1),
  mimeType: z.enum(UPLOAD_MIME_TYPES),
  byteSize: z.number().int().positive().max(MAX_UPLOAD_BYTES),
  // Absent for PDFs — canvas re-encoding only applies to photo captures.
  width: z.number().int().positive().nullable(),
  height: z.number().int().positive().nullable(),
  // Client-generated once per capture attempt; retries reuse it so a flaky
  // network never produces a duplicate documents row (unique in the schema).
  idempotencyKey: z.uuid(),
})
export type CreateDocumentInput = z.infer<typeof CreateDocumentSchema>

// ── Auth ─────────────────────────────────────────────────────────────────────

export const RegisterSchema = z.object({
  familyName: z
    .string()
    .trim()
    .min(1, 'Give your family space a name')
    .max(80, 'Keep the name under 80 characters'),
  email: z.email('Enter a valid email address'),
  password: z.string().min(8, 'Password must be at least 8 characters').max(72),
})
export type RegisterInput = z.infer<typeof RegisterSchema>

export const LoginSchema = z.object({
  email: z.email('Enter a valid email address'),
  password: z.string().min(1, 'Enter your password'),
})
export type LoginInput = z.infer<typeof LoginSchema>

// ── Profiles ─────────────────────────────────────────────────────────────────

export const ProfileSchema = z.object({
  name: z.string().trim().min(1, 'Every profile needs a name').max(80),
  // ISO date string from <input type="date">; optional — dob is never required
  dob: z.iso.date('Enter a valid date').optional().or(z.literal('').transform(() => undefined)),
  sex: z.enum(SEXES).optional().or(z.literal('').transform(() => undefined)),
  color: z.enum(PROFILE_COLORS).default('accent'),
})
export type ProfileInput = z.infer<typeof ProfileSchema>

// PIN is a 4-digit privacy lock within the family — not a security credential
// (see SYSTEM_DESIGN §D). Account password is the real boundary.
const Pin4 = z.string().regex(/^\d{4}$/, 'PIN is exactly 4 digits')

// Unlock + first-time set (no existing PIN → nothing to verify against).
export const PinSchema = z.object({ pin: Pin4 })
export type PinInput = z.infer<typeof PinSchema>

// Changing or removing an EXISTING PIN requires proof of scope:
//   profile-holder → knows the current PIN
//   account-holder → re-enters the account password (the recovery path;
//                    identity can't prove this — the family shares one login)
const VerifyByPin = z.object({ verifyWith: z.literal('pin'), currentPin: Pin4 })
const VerifyByPassword = z.object({
  verifyWith: z.literal('password'),
  accountPassword: z.string().min(1, 'Enter the account password'),
})

export const ChangePinSchema = z.discriminatedUnion('verifyWith', [
  VerifyByPin.extend({ newPin: Pin4 }),
  VerifyByPassword.extend({ newPin: Pin4 }),
])
export type ChangePinInput = z.infer<typeof ChangePinSchema>

export const RemovePinSchema = z.discriminatedUnion('verifyWith', [VerifyByPin, VerifyByPassword])
export type RemovePinInput = z.infer<typeof RemovePinSchema>

// ── Organize (the AI pipeline contract, D-012) ───────────────────────────────
// One `generateText + Output.object(OrganizeSchema)` call per document. The
// output splits across two tables: classification + doc-level fields → the
// `documents` row; the explanation + atomic cited facts → `document_explanations`.
//
// Two hard rules are encoded here and enforced again in the prompt:
//   • Verbatim-or-null (Rule 2): every extracted value is copied as written on
//     the document or `null` — never inferred, normalized into existence, or
//     defaulted. `.nullable()` is deliberate on every non-classification field.
//   • Explain-never-advise (Rule 1): term explanations DEFINE the term; they
//     never interpret the patient's specific value. Printed abnormality flags
//     are copied verbatim into `flag_as_written` (what the document says), never
//     generated by us; the UI renders them neutral (D-012).
//
// These item shapes are the atomic, agent-consumable facts (D-012): each is a
// standalone cited record, not prose trapped in `what_it_says`. `document_id`
// on the explanation row is the citation; recency joins to `documents.document_date`.

const TermSchema = z.object({
  term: z.string(), // verbatim jargon as printed, e.g. "HbA1c"
  plain_explanation: z.string(), // generic definition; never interprets this patient's value
})
export type Term = z.infer<typeof TermSchema>

const MedicationSchema = z.object({
  name: z.string(), // verbatim
  strength: z.string().nullable(), // "500mg" or null
  frequency: z.string().nullable(), // "twice daily" or null
  form: z.string().nullable(), // "tablet" or null
})
export type Medication = z.infer<typeof MedicationSchema>

const LabTestSchema = z.object({
  name: z.string(), // "Fasting blood glucose" verbatim
  value: z.string().nullable(), // "126" verbatim; kept as string — never coerced
  unit: z.string().nullable(), // "mg/dL" verbatim
  reference_range: z.string().nullable(), // "70-100" as printed; never compared to value
  flag_as_written: z.string().nullable(), // "HIGH"/"H"/"↑" copied verbatim; never generated
})
export type LabTest = z.infer<typeof LabTestSchema>

export const OrganizeSchema = z.object({
  // Unreadable/corrupt scan → false, all other fields empty/null; the pipeline
  // sets status='needs_review' and the document stays visible (capture is sacred).
  readable: z.boolean(),

  // → documents (classification + verbatim-or-null document-level fields)
  doc_type: z.enum(DOC_TYPES),
  title: z.string(), // short human label for the timeline card
  title_is_guessed: z.boolean(), // true when no title is printed on the document
  document_date: z.iso.date().nullable(), // the document's own date as ISO; never captured_at
  doctor_name: z.string().nullable(),
  facility_name: z.string().nullable(),
  patient_name_as_written: z.string().nullable(), // Rule-4 clinical-noun exemption

  // → document_explanations (D-012 atomic cited facts + human summary)
  what_it_says: z.string(), // plain-language SUMMARY only; adds no fact absent from the fields below
  terms: z.array(TermSchema),
  medications_as_written: z.array(MedicationSchema),
  tests_as_written: z.array(LabTestSchema),
})
export type OrganizeOutput = z.infer<typeof OrganizeSchema>
