/**
 * Shared env loader for the RLS proof tests (__tests__/rls/*). These tests
 * create and delete real users, families, profiles, and storage objects, so
 * they must only ever run against a local Supabase instance.
 *
 * Reads .env.test.local (gitignored, generated by
 * `node scripts/write-test-env.mjs`) — deliberately NOT .env.local, which
 * holds this project's real production credentials. Found 2026-09-08: a
 * bare `pnpm test` run in a shell with no env exported fell through to
 * .env.local and ran the RLS proof suite against production. The `afterAll`
 * cleanup happened to run and left nothing behind that time, but a crash
 * before cleanup would not have been so lucky — hence refusing to proceed
 * at all rather than trusting cleanup to save a run against the wrong DB.
 */
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const LOCAL_URL_PATTERN = /^https?:\/\/(127\.0\.0\.1|localhost|0\.0\.0\.0)(:\d+)?\/?$/

function loadEnvFile(filename: string) {
  try {
    const raw = readFileSync(join(process.cwd(), filename), 'utf8')
    for (const line of raw.split('\n')) {
      const eq = line.indexOf('=')
      if (eq === -1 || line.startsWith('#')) continue
      const key = line.slice(0, eq).trim()
      const value = line.slice(eq + 1).split('#')[0].trim()
      if (!process.env[key]) process.env[key] = value
    }
  } catch {
    // missing is fine — CI sets these vars directly in the environment
  }
}

export type SupabaseTestEnv = {
  url: string
  anonKey: string
  serviceKey: string
}

export function loadSupabaseTestEnv(): SupabaseTestEnv {
  if (!process.env.NEXT_PUBLIC_SUPABASE_URL) {
    loadEnvFile('.env.test.local')
  }

  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  const anonKey = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY

  if (!url || !anonKey || !serviceKey) {
    throw new Error(
      'RLS proof tests need a local Supabase instance. Run `npx supabase start` then ' +
        '`node scripts/write-test-env.mjs` to generate .env.test.local, or export ' +
        'NEXT_PUBLIC_SUPABASE_URL / NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY / ' +
        'SUPABASE_SERVICE_ROLE_KEY yourself (this is how CI does it).'
    )
  }

  if (!LOCAL_URL_PATTERN.test(url)) {
    throw new Error(
      `RLS proof tests refuse to run against a non-local Supabase URL (got "${url}"). ` +
        "These tests create and delete real users, families, and storage objects — " +
        'never point them at production, including by accident via .env.local. Run ' +
        '`npx supabase start` then `node scripts/write-test-env.mjs` to generate a ' +
        'local .env.test.local instead.'
    )
  }

  return { url, anonKey, serviceKey }
}
